/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'austinm' at '3/1/17 3:13 PM' with Gradle 2.14.1
 *
 * @author austinm, @date 3/1/17 3:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
